version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=default_db_name
      - DB_USER=default_db_user
      - DB_PASSWORD=default_db_password
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DB=default_db_name
      - POSTGRES_USER=default_db_user
      - POSTGRES_PASSWORD=default_db_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
